### ISSUE TITLE
[BUG]A minimum of 3 observations are needed to run an ADF with trend n and the user-specified number of lags.

### ISSUE THREAD

**Issue by masafumimori** [AdamWLabs/tsfracdiff#1]
**Describe the bug**
This should not be a bug or that kind of sort I assume, but I wanted to ask you about it.

This package is really useful and thank you for creating this.

But I ran into an error saying
`A minimum of 3 observations are needed to run an ADF with trend n and the user-specified number of lags.`
when I run `Fit` or `FitTransform` to dataframe with shape like (210, 5).

It works fine like when rows are enough (over 3,000 or so) in the same kind of time series data.
I am using financial time series data.

**To Reproduce**
1. get time series data from yfinance.
2. separate data into test and train. test data length should be around 200 like in my case.
3. create FractionalDifferentiator object with `unitRootTest="ADF"` param
4. run `Fit` on test data

**Expected behavior**
Not sure.
Preferrably transform data if possible.
Or could you allow us to change threshold/cutoff lag so it can prevent limited data from losing too much?

Thank you.

**Comment by adamvvu** [comment]
Hey @masafumimori, 

My best guess for the error would be that there simply isn't enough observations to automatically compute the optimal order.

Recall that if a time series is integrated of order $I(0)$, then it is already (weakly) stationary and does not need any transformation. If it is of order $I(1)$, then we can just take the first difference so we will lose the first data point. However for fractional orders $I(d)$, the number of lags required can be much larger. 

The current implementation (v1.0.3) uses a minimum weight threshold of 0.0001, but I just pushed a new version (v1.0.4) which allows you to make `memoryThreshold` larger so that less lags are required at the cost of some precision. E.g.
```
fracdiff = FractionalDifferentiator( memoryThreshold=0.001, #other args )
```
![image](https://user-images.githubusercontent.com/34133796/218087756-5c2e1a09-2379-4a50-b15d-afd39c63b00d.png)

But keep in mind that the power of the unit root tests may be fairly low for small samples, so it's not a perfect solution.
